# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:
 
  app:
    image: hantsy/rest-many-to-many-example
    depends_on:
      - db
    # https://docs.docker.com/compose/startup-order/
    # command: ./wait-for-it.sh "db:3306" -t  10 #-- echo "MySQL is up"
    ports:
      - "9999:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb"
