-- use master;

CREATE TABLE IF NOT EXISTS TENANT_CONFIGS(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
TENANT_ID VARCHAR(255) NOT NULL,
URL VARCHAR(255) NOT NULL
);

-- insert initial data
DELETE FROM TENANT_CONFIGS;

INSERT INTO TENANT_CONFIGS(TENANT_ID,URL)
VALUES 
('tenant1', 'r2dbc:postgresql://user:password@localhost:5432/tenant1'),
('tenant2', 'r2dbc:postgresql://user:password@localhost:15432/tenant2');

-- default tenant schema.
CREATE TABLE IF NOT EXISTS CUSTOMERS(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS ORDERS(
ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
CUST_ID INTEGER NOT NULL,
AMOUNT REAL NOT NULL
);

-- INSERT SAMPLE DATA
DELETE FROM CUSTOMERS;
INSERT INTO CUSTOMERS(FIRST_NAME, LAST_NAME) VALUES ('hantsy@master', 'bai');