CREATE TABLE IF NOT EXISTS todos
(
    id    SERIAL,
    title VARCHAR(200)
);

ALTER TABLE todos
    DROP CONSTRAINT IF EXISTS todos_pk;
ALTER TABLE todos
    ADD CONSTRAINT todos_pk PRIMARY KEY (id);
