CREATE SCHEMA IF NOT EXISTS tenant1 ;
SHOW search_path;
SET search_path  TO tenant1;

CREATE SEQUENCE IF NOT EXISTS CUSTOMERS_ID_SEQ;

CREATE TABLE IF NOT EXISTS CUSTOMERS(
ID integer NOT NULL PRIMARY KEY DEFAULT nextval('CUSTOMERS_ID_SEQ') ,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL
);

ALTER SEQUENCE CUSTOMERS_ID_SEQ OWNED BY CUSTOMERS.ID;


CREATE SEQUENCE IF NOT EXISTS ORDERS_ID_SEQ;

CREATE TABLE IF NOT EXISTS ORDERS(
ID integer NOT NULL PRIMARY KEY DEFAULT nextval('ORDERS_ID_SEQ') ,
CUST_ID INTEGER NOT NULL,
AMOUNT DECIMAL NOT NULL
);

ALTER SEQUENCE ORDERS_ID_SEQ OWNED BY ORDERS.ID;

