# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:

  #see: https://github.com/maildev/maildev
  smtp:
    image: djfarrelly/maildev
    ports:
      - "25:25"