# see https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.5" # specify docker-compose version, v3.5 is compatible with docker 17.12.0+

# Define the services/containers to be run
services:
  oracledb:
    image: oracle/database:18.4.0-xe
    environment:
      - "ORACLE_PWD:Passw0rd"
#      - "ORACLE_CHARACTERSET:AL32UTF8" # default is AL32UTF8
    volumes:
      - ./oradata:/opt/oracle/oradata # persistent oracle database data.
    ports:
      - 1521:1521 
 #     - 8080:8080 # apex
 #     - 5500:5500 # oemexpress
