name: build
on:
  push:
    paths-ignore:
      - "rest-many-to-many/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  modular-jpms:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn -B -q clean verify --file modular-jpms/pom.xml
  amqp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up RabbitMQ(via Docker Compose)
        run: |
          cd amqp
          docker-compose up -d
          sleep 10
          docker ps -a
      - name: Build with Maven(hello-amqp)
        run: |
          mvn -B -q clean package --file amqp/hello-amqp/pom.xml
          mvn -B -q verify --file amqp/hello-amqp/pom.xml -Pit
      - name: Build with Maven(spring-messaging-amqp)
        run: |
          mvn -B -q clean package --file amqp/spring-messaging-amqp/pom.xml
          mvn -B -q verify --file amqp/spring-messaging-amqp/pom.xml -Pit
      - name: Build with Maven(cafe-integration-dsl-amqp)
        run: |
          mvn -B -q clean package --file amqp/cafe-integration-dsl-amqp/pom.xml      
  programming-models:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Postgres(via Docker Compose)
        run: |
          cd programming-models
          docker-compose up -d
          sleep 10
          docker ps -a
      - name: Build with Maven(webmvc)
        run: |
          mvn -B -q clean package --file programming-models/webmvc/pom.xml
          mvn -B -q verify --file programming-models/webmvc/pom.xml -Pit
      - name: Build with Maven(webflux)
        run: |
          mvn -B -q clean package --file programming-models/webflux/pom.xml
          mvn -B -q verify --file programming-models/webflux/pom.xml -Pit
      - name: Build with Maven(webmvc-fn)
        run: |
          mvn -B -q clean package --file programming-models/webmvc-fn/pom.xml
          mvn -B -q verify --file programming-models/webmvc-fn/pom.xml -Pit          
      - name: Build with Maven(webflux-fn)
        run: |
          mvn -B -q clean package --file programming-models/webflux-fn/pom.xml
          mvn -B -q verify --file programming-models/webflux-fn/pom.xml -Pit     
      - name: Build with Maven(webflux-ktco)
        run: |
          mvn -B -q clean package --file programming-models/webflux-ktco/pom.xml
          mvn -B -q verify --file programming-models/webflux-ktco/pom.xml -Pit     
      - name: Build with Maven(webflux-ktco-fn)
        run: |
          mvn -B -q clean package --file programming-models/webflux-ktco-fn/pom.xml
          mvn -B -q verify --file programming-models/webflux-ktco-fn/pom.xml -Pit        
