name: hibernate-reactive-mutiny
on:
  push:
    paths:
      - "hibernate-reactive-mutiny/**"
    branches: [master]
  pull_request:
    paths:
      - "hibernate-reactive-mutiny/**"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up Postgres(via Docker Compose)
        run: |
          cd hibernate-reactive-mutiny
          docker-compose up -d
          sleep 10
          docker ps -a
      - name: Build with Maven
        run: |
          mvn -B -q clean package --file hibernate-reactive-mutiny/pom.xml
          mvn -B -q verify --file hibernate-reactive-mutiny/pom.xml -Pit
     
