name: hibernate-reactive-mutiny-oracle
on:
  push:
    paths:
      - "hibernate-reactive-mutiny-oracle/**"
    branches: [master]
  pull_request:
    paths:
      - "hibernate-reactive-mutiny-oracle/**"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"
          cache: "maven"
      - name: Set up Oracle(via Docker Compose)
        run: |
          cd hibernate-reactive-mutiny-oracle
          docker-compose up -d
          sleep 10
          docker ps -a
      - name: Build with Maven
        run: |
          mvn -B -q clean package --file hibernate-reactive-mutiny-oracle/pom.xml
          mvn -B -q verify --file hibernate-reactive-mutiny-oracle/pom.xml -Pit
     
