name: integration-sftp
on:
  push:
    paths:
      - "integration-sftp/**"
    branches: [master]
  pull_request:
    paths:
      - "integration-sftp/**"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "zulu"
          cache: "maven"
      - name: Build with Maven
        run: |
          mvn -B -q clean test
     
