name: programming-models
on:
  push:
    paths:
      - "programming-models/**"
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "zulu"
          cache: "maven"
      - name: Build with Maven
        run: |
          cd programming-models
          ./mvnd -B -q clean test
