name: springdoc-gateway
on:
  push:
    paths:
      - "springdoc-gateway/**"
    branches: [master]
  pull_request:
    paths:
      - "springdoc-gateway/**"
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"
      - name: Cache Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: |
          mvn -B -q clean package spring-boot:run --file springdoc-gateway/customers/pom.xml &
          mvn -B -q clean package spring-boot:run --file springdoc-gateway/orders/pom.xml &
          sleep 5
          mvn -B -q clean verify --file springdoc-gateway/gateway/pom.xml
     
